### ISSUE TITLE
Offer of help

### ISSUE THREAD

**Issue by CatInCosmicSpace** [beiyuouo/hainanubeamer#1]
Hello, @beiyuouo!

I saw that you used actions from my [repository](https://github.com/CatInCosmicSpace/latex-template), but apparently there was not enough functionality for your case. I more or less figured out using GitHub Workflows while I was making my template for Bauman Moscow State Technical University, so I can help you set it up for your case. May I help you with this? :)

Best regards,
Alena.

**Comment by yyyanbj** [comment]
Hi, Alena!

I would be glad if you can help me! btw, I'm really a noob at using GitHub Workflow to compile LaTeX. 🤣

Best wishes,
Bingjie

**Comment by CatInCosmicSpace** [comment]
Hello again)

I suggest a #2. Also I added some comments FYI.

Feel free to ask any questions)

**Comment by yyyanbj** [comment]
It’s very kind of you to help me!

**Comment by CatInCosmicSpace** [comment]
You are welcome 😊
